import { mkdir, readFile, writeFile } from "node:fs/promises";

const catalog = JSON.parse(
  await readFile(new URL("../data/resources.json", import.meta.url), "utf8"),
);
const docs = new URL("../docs/", import.meta.url);
await mkdir(docs, { recursive: true });
await writeFile(new URL("catalog.json", docs), `${JSON.stringify(catalog, null, 2)}\n`, "utf8");
await writeFile(
  new URL("catalog.js", docs),
  `/* Generated by npm run build. Do not edit directly. */\nwindow.CODEX_RESOURCE_CATALOG = ${JSON.stringify(catalog)};\n`,
  "utf8",
);
console.log(`Built static catalog with ${catalog.resources.length} resources.`);
